name = "onyx-hair-salon"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
API_URL = "https://hair-salon-api.bold-bush-66e8.workers.dev"
